import { useI18n } from '../i18n'

/**
 * Copy for the living-map world surface, kept beside the world code so the
 * whole experience can be promoted or retired as one unit. UI chrome is
 * bilingual; sample-world data (spot names, mission stories) stays English
 * for now, matching the dashboard convention.
 */

const en = {
  // Shared chrome
  'world.sampleTag': 'Sample',
  'world.sampleNote': 'Demo world: real public listings plus sample neighbors that show how the network moves.',
  'world.demoAction': 'Demo action. Nothing is sent or saved beyond this browser.',
  'world.back': 'Back',
  'world.close': 'Close',
  'world.openMap': 'Back to the map',
  'world.standardMap': 'Classic food finder',
  'world.mapLabel': 'Living map of the Eastside Circle',
  'world.pulseButton': 'Yuhm Pulse',
  'world.profileButton': 'Your presence',
  'world.circleLabel': 'Your Yuhm Circle',
  'world.sheetHandle': 'Resize the panel',

  // Layers
  'world.layers.label': 'Map layers',
  'world.layers.all': 'Everything',
  'world.layers.grow': 'Grow',
  'world.layers.make': 'Make',
  'world.layers.share': 'Share',
  'world.layers.move': 'Move',
  'world.layers.commons': 'Commons',
  'world.lens.grow': 'The Grow lens: farms and gardens raising food inside the circle.',
  'world.lens.make': 'The Make lens: kitchens and markets turning food into meals.',
  'world.lens.share': 'The Share lens: tables and shelves where food reaches neighbors.',
  'world.lens.move': 'The Move lens: the routes and couriers keeping food flowing.',
  'world.lens.commons': 'The Commons lens: the real public food directory, open to everyone.',
  'world.lens.emptyMissions': 'No open invitations under this lens right now.',

  // Onboarding
  'world.intro.kicker': 'Welcome to the yuhm world',
  'world.intro.title': 'Find your local yuhm.',
  'world.intro.copy': 'Real people near you grow, cook, carry, and share food every week. This living map shows the network moving, and where you fit in it.',
  'world.intro.start': 'Step in',
  'world.intro.skip': 'Skip to the map',
  'world.role.title': 'How do you want to take part?',
  'world.role.copy': 'Pick what fits today. You can do all of it, and change anytime.',
  'world.role.eat': 'Eat',
  'world.role.eatCopy': 'Find food with a story',
  'world.role.grow': 'Grow',
  'world.role.growCopy': 'Garden, farm, share seeds',
  'world.role.make': 'Make',
  'world.role.makeCopy': 'Cook, bake, preserve',
  'world.role.move': 'Move',
  'world.role.moveCopy': 'Carry food on shared runs',
  'world.role.share': 'Share',
  'world.role.shareCopy': 'Host tables, stock shelves',
  'world.role.organize': 'Organize',
  'world.role.organizeCopy': 'Weave the neighborhood',
  'world.privacy.title': 'Where should your circle be?',
  'world.privacy.copy': 'Your location stays on this device. The map only ever shows your approximate neighborhood, never your address.',
  'world.privacy.use': 'Use my location',
  'world.privacy.stay': 'Stay at neighborhood level',
  'world.reveal.kicker': 'You are in',
  'world.reveal.copy': 'Six sample neighbors and the real public food directory are already on your map.',
  'world.reveal.first': 'Your first invitation',
  'world.reveal.open': 'Open the living map',

  // Discover sheet
  'world.discover.hello': 'Happening in your circle',
  'world.discover.missions': 'Open invitations',
  'world.discover.missionsCopy': 'Real activities, sample data. Join one to walk the loop.',
  'world.discover.pool': 'Yuhm Pool filling up',
  'world.discover.run': 'Next Yuhm Run',
  'world.discover.spots': 'Yuhm Spots near you',
  'world.discover.directory': 'Public food directory',
  'world.discover.directoryCopy': 'Real listings. Confirm hours before traveling.',
  'world.discover.seePulse': 'See the Yuhm Pulse',

  // Focused-flow handoffs
  'world.more.title': 'More ways to take part',
  'world.more.copy': 'The focused yuhm flows, outside the demo world.',
  'world.more.find': 'Find food',
  'world.more.contribute': 'Contribute',
  'world.more.gather': 'Gather',
  'world.more.requests': 'Requests',
  'world.more.signIn': 'Sign in',
  'world.more.advanced': 'Command center',

  // Spot card
  'world.spot.offers': 'Available or needed',
  'world.spot.people': 'Who is here',
  'world.spot.window': 'Window',
  'world.spot.contribution': 'Contribution',
  'world.spot.impact': 'Circle impact',
  'world.spot.join': 'Join in',
  'world.spot.route': 'Preview the route',
  'world.spot.navigate': 'Directions',
  'world.spot.verified': 'Verified listing',
  'world.spot.community': 'Community report',
  'world.spot.confirm': 'Confirm current hours before traveling.',
  'world.spot.journey': 'A food journey through this spot',

  // Mission flow
  'world.mission.invite': 'Invitation',
  'world.mission.left': '{count} spots open',
  'world.mission.leftOne': '1 spot open',
  'world.mission.with': 'You would join',
  'world.mission.join': 'Count me in',
  'world.mission.joined': 'You are in',
  'world.mission.coordinate': 'The plan',
  'world.mission.done': 'Mark it complete',
  'world.mission.completed': 'Completed',
  'world.mission.routeNote': 'Your leg glows on the map.',

  // Pool
  'world.pool.kicker': 'Yuhm Pool',
  'world.pool.copy': 'Neighbors order together so one route serves everyone.',
  'world.pool.share': 'Take a share',
  'world.pool.shared': 'Share reserved',
  'world.pool.closes': 'Pool closes {when}',
  'world.pool.route': 'Rides on the {run}',
  'world.pool.merge': 'As neighbors join, their pickups merge into one flowing route.',

  // Run
  'world.run.kicker': 'Yuhm Run',
  'world.run.stops': 'Route',
  'world.run.carried': 'Carried by',
  'world.run.saved': '{miles} miles, {trips} car trips saved',
  'world.run.leg': 'Carry a leg',
  'world.run.compostLeg': 'Return leg',

  // Pulse
  'world.pulse.kicker': 'Yuhm Pulse',
  'world.pulse.title': 'The circle this week',
  'world.pulse.copy': 'Sample numbers showing the shape of a healthy week.',
  'world.pulse.meals': 'meals shared',
  'world.pulse.rescued': 'lb of food rescued',
  'world.pulse.miles': 'car miles saved by pooling',
  'world.pulse.compost': 'lb returned to the soil',
  'world.pulse.neighbors': 'neighbors took part',
  'world.pulse.connections': 'first-time connections',

  // Profile
  'world.profile.kicker': 'Your presence',
  'world.profile.you': 'You',
  'world.profile.roleLabel': 'Showing up to',
  'world.profile.garden': 'Your network garden',
  'world.profile.gardenCopy': 'It grows with every contribution, not with points.',
  'world.profile.contributions': 'Contributions in this demo',
  'world.profile.privacy': 'Only your first name and role are ever visible. Your location stays on this device.',
  'world.profile.replay': 'Replay the welcome',

  // Gratitude
  'world.thanks.kicker': 'The circle felt that',
  'world.thanks.title': 'Thank you.',
  'world.thanks.from': 'A note from {name}',
  'world.thanks.note': 'That handoff kept the loop moving. Come by the table on Sunday, there is always a seat.',
  'world.thanks.impact': 'What just happened',
  'world.thanks.return': 'Return to the circle',
  'world.thanks.regen': 'One more turn: bring your scraps back and the soil eats too.',
}

const es: Record<WorldKey, string> = {
  'world.sampleTag': 'Ejemplo',
  'world.sampleNote': 'Mundo de demostración: listados públicos reales más vecinos de ejemplo que muestran cómo se mueve la red.',
  'world.demoAction': 'Acción de demostración. No se envía ni se guarda nada fuera de este navegador.',
  'world.back': 'Atrás',
  'world.close': 'Cerrar',
  'world.openMap': 'Volver al mapa',
  'world.standardMap': 'Buscador clásico de comida',
  'world.mapLabel': 'Mapa vivo del Círculo del Este',
  'world.pulseButton': 'Pulso Yuhm',
  'world.profileButton': 'Tu presencia',
  'world.circleLabel': 'Tu Círculo Yuhm',
  'world.sheetHandle': 'Ajustar el panel',

  'world.layers.label': 'Capas del mapa',
  'world.layers.all': 'Todo',
  'world.layers.grow': 'Cultivar',
  'world.layers.make': 'Cocinar',
  'world.layers.share': 'Compartir',
  'world.layers.move': 'Mover',
  'world.layers.commons': 'Comunes',
  'world.lens.grow': 'Lente Cultivar: granjas y huertos que crían comida dentro del círculo.',
  'world.lens.make': 'Lente Cocinar: cocinas y mercados que convierten comida en platos.',
  'world.lens.share': 'Lente Compartir: mesas y estantes donde la comida llega a los vecinos.',
  'world.lens.move': 'Lente Mover: las rutas y mensajeros que mantienen la comida en movimiento.',
  'world.lens.commons': 'Lente Comunes: el directorio público real de comida, abierto a todos.',
  'world.lens.emptyMissions': 'No hay invitaciones abiertas bajo esta lente por ahora.',

  'world.intro.kicker': 'Bienvenido al mundo yuhm',
  'world.intro.title': 'Encuentra tu yuhm local.',
  'world.intro.copy': 'Gente real cerca de ti cultiva, cocina, transporta y comparte comida cada semana. Este mapa vivo muestra la red en movimiento, y tu lugar en ella.',
  'world.intro.start': 'Entrar',
  'world.intro.skip': 'Ir directo al mapa',
  'world.role.title': '¿Cómo quieres participar?',
  'world.role.copy': 'Elige lo que te quede hoy. Puedes hacerlo todo, y cambiar cuando quieras.',
  'world.role.eat': 'Comer',
  'world.role.eatCopy': 'Comida con historia',
  'world.role.grow': 'Cultivar',
  'world.role.growCopy': 'Huerto, granja, semillas',
  'world.role.make': 'Cocinar',
  'world.role.makeCopy': 'Cocina, hornea, conserva',
  'world.role.move': 'Mover',
  'world.role.moveCopy': 'Lleva comida en rutas compartidas',
  'world.role.share': 'Compartir',
  'world.role.shareCopy': 'Mesas y estantes comunitarios',
  'world.role.organize': 'Organizar',
  'world.role.organizeCopy': 'Teje el vecindario',
  'world.privacy.title': '¿Dónde estará tu círculo?',
  'world.privacy.copy': 'Tu ubicación se queda en este dispositivo. El mapa solo muestra tu vecindario aproximado, nunca tu dirección.',
  'world.privacy.use': 'Usar mi ubicación',
  'world.privacy.stay': 'Quedarme a nivel de vecindario',
  'world.reveal.kicker': 'Estás en',
  'world.reveal.copy': 'Seis vecinos de ejemplo y el directorio público real de comida ya están en tu mapa.',
  'world.reveal.first': 'Tu primera invitación',
  'world.reveal.open': 'Abrir el mapa vivo',

  'world.discover.hello': 'Pasando en tu círculo',
  'world.discover.missions': 'Invitaciones abiertas',
  'world.discover.missionsCopy': 'Actividades reales, datos de ejemplo. Únete a una para recorrer el ciclo.',
  'world.discover.pool': 'Pool Yuhm llenándose',
  'world.discover.run': 'Próxima Ruta Yuhm',
  'world.discover.spots': 'Puntos Yuhm cerca de ti',
  'world.discover.directory': 'Directorio público de comida',
  'world.discover.directoryCopy': 'Listados reales. Confirma horarios antes de viajar.',
  'world.discover.seePulse': 'Ver el Pulso Yuhm',

  'world.more.title': 'Más formas de participar',
  'world.more.copy': 'Los flujos enfocados de yuhm, fuera del mundo de demostración.',
  'world.more.find': 'Buscar comida',
  'world.more.contribute': 'Contribuir',
  'world.more.gather': 'Reunirse',
  'world.more.requests': 'Solicitudes',
  'world.more.signIn': 'Iniciar sesión',
  'world.more.advanced': 'Centro de mando',

  'world.spot.offers': 'Disponible o necesario',
  'world.spot.people': 'Quién está aquí',
  'world.spot.window': 'Horario',
  'world.spot.contribution': 'Contribución',
  'world.spot.impact': 'Impacto en el círculo',
  'world.spot.join': 'Unirme',
  'world.spot.route': 'Ver la ruta',
  'world.spot.navigate': 'Cómo llegar',
  'world.spot.verified': 'Listado verificado',
  'world.spot.community': 'Reporte comunitario',
  'world.spot.confirm': 'Confirma los horarios antes de viajar.',
  'world.spot.journey': 'Un viaje de comida por este punto',

  'world.mission.invite': 'Invitación',
  'world.mission.left': '{count} lugares abiertos',
  'world.mission.leftOne': '1 lugar abierto',
  'world.mission.with': 'Te unirías a',
  'world.mission.join': 'Cuenta conmigo',
  'world.mission.joined': 'Ya estás dentro',
  'world.mission.coordinate': 'El plan',
  'world.mission.done': 'Marcar como completada',
  'world.mission.completed': 'Completada',
  'world.mission.routeNote': 'Tu tramo brilla en el mapa.',

  'world.pool.kicker': 'Pool Yuhm',
  'world.pool.copy': 'Los vecinos piden juntos para que una sola ruta sirva a todos.',
  'world.pool.share': 'Tomar una parte',
  'world.pool.shared': 'Parte reservada',
  'world.pool.closes': 'El pool cierra {when}',
  'world.pool.route': 'Viaja en la {run}',
  'world.pool.merge': 'Cuando los vecinos se unen, sus recogidas se funden en una sola ruta.',

  'world.run.kicker': 'Ruta Yuhm',
  'world.run.stops': 'Ruta',
  'world.run.carried': 'A cargo de',
  'world.run.saved': '{miles} millas, {trips} viajes en coche ahorrados',
  'world.run.leg': 'Llevar un tramo',
  'world.run.compostLeg': 'Tramo de retorno',

  'world.pulse.kicker': 'Pulso Yuhm',
  'world.pulse.title': 'El círculo esta semana',
  'world.pulse.copy': 'Números de ejemplo que muestran la forma de una semana sana.',
  'world.pulse.meals': 'comidas compartidas',
  'world.pulse.rescued': 'lb de comida rescatada',
  'world.pulse.miles': 'millas de coche ahorradas',
  'world.pulse.compost': 'lb devueltas a la tierra',
  'world.pulse.neighbors': 'vecinos participaron',
  'world.pulse.connections': 'conexiones nuevas',

  'world.profile.kicker': 'Tu presencia',
  'world.profile.you': 'Tú',
  'world.profile.roleLabel': 'Participas para',
  'world.profile.garden': 'Tu jardín de red',
  'world.profile.gardenCopy': 'Crece con cada contribución, no con puntos.',
  'world.profile.contributions': 'Contribuciones en esta demo',
  'world.profile.privacy': 'Solo tu nombre de pila y tu rol son visibles. Tu ubicación se queda en este dispositivo.',
  'world.profile.replay': 'Repetir la bienvenida',

  'world.thanks.kicker': 'El círculo lo sintió',
  'world.thanks.title': 'Gracias.',
  'world.thanks.from': 'Una nota de {name}',
  'world.thanks.note': 'Esa entrega mantuvo el ciclo en movimiento. Pásate por la mesa el domingo, siempre hay un lugar.',
  'world.thanks.impact': 'Lo que acaba de pasar',
  'world.thanks.return': 'Volver al círculo',
  'world.thanks.regen': 'Una vuelta más: trae tus sobras y la tierra también come.',
}

export type WorldKey = keyof typeof en

const catalogs = { en, es }

export function useWorldText() {
  const { lang } = useI18n()
  return (key: WorldKey, vars?: Record<string, string | number>) => {
    let message = catalogs[lang][key] ?? en[key]
    if (vars) for (const [name, value] of Object.entries(vars)) message = message.split(`{${name}}`).join(String(value))
    return message
  }
}
